// Created by: Wouter Legiest

pub const NAME_LIST: [&'static str; 48]= [
"Wouter Legiest",
"Jan-Pieter D'Anvers", 
"Ingrid Verbauwhede",  
"Nam-Luc Tran",
"Bojan Spasic",
"Biff Tannen",
"Hans Gruber", 
"Freddy Krueger",
"Hannibal Lecter",
"Indiana Jones",
"Vito Corleone",
"Marty McFly",
"Peter Venkman",
"Egon Spengler",
"Winston Zeddemore",
"Lorraine Baines",
"Ray Stantz",
"Ellen Ripley",
"John McClane",
"Tony Stark",
"Peter Parker",
"Steve Rogers",
"Thor Odinson",
"Natasha Romanoff",
"Clint Barton",
"Nick Fury",
"Phil Coulson",
"Rocky Balboa",
"Bilbo Baggins",
"Tony Montana",
"Samwise Gamgee",
"Ethan Hunt", 
"James Bond",
"Bruce Wayne",
"Clark Kent",
"Diana Prince",
"Arthur Curry",
"Barry Allen",
"Hal Jordan",
"Logan Howlett",
"Charles Xavier",
"Jean Grey",
"Erik Lehnsherr",
"Stephen Strange",
"Bruce Banner",
"Peggy Carter",
"Norman Bates",
"Rick Deckard"
];

pub const NAME_LIST_8char: [&'static str; 48]= [
"bvdyurfg",
"htueoirw",
"jsiwoqaz",
"kmnlopij",
"qazwsxed",
"rfvtgbyh",
"nuijmbko",
"plokmijn",
"zasxdcfv",
"tgbnhyuj",
"mkoijnuh",
"ygtfrdes",
"wqazxcds",
"evfrbgtg",
"nhyujmki",
"olpkiujm",
"zxdcfvgb",
"hnjmklio",
"asdfghjk",
"cvbnmklo",
"wertfgyh",
"bnmklpoi",
"qsdfgyui",
"xcvbnmlo",
"ertyuiop",
"dfghjklm",
"zxcvbnmk",
"asdfghjk",
"qwertzui",
"yxcvbnmq",
"poiuytre",
"lkjhgfdsa",
"mnbvcxzp",
"oiuytrew",
"jklpoiuy",
"hgfdsazx",
"bnmkiuyt",
"vgytfcrd",
"wsxedcrf",
"edcvfrgt",
"rfvbgtnh",
"tgnhymju",
"gyujmki8",
"ujmki9ol",
"nhbgvfcd",
"mkoijnlp",
"asdfrewq",
"zxcvlkjh",
];
